export const AUTH_ADMIN_LOGIN = 'AUTH_ADMIN_LOGIN';
export const AUTH_ADMIN_LOAD = 'AUTH_ADMIN_LOAD';
export const AUTH_ADMIN_FAILURE = 'AUTH_ADMIN_FAILURE';
export const AUTH_ADMIN_LOGOUT = 'AUTH_ADMIN_LOGOUT';
