export const INDEX_PAGE_LOAD_DATA_START = 'INDEX_PAGE_LOAD_DATA_START';
export const INDEX_PAGE_LOAD_DATA_LOAD = 'INDEX_PAGE_LOAD_DATA_LOAD';
export const INDEX_PAGE_LOAD_DATA_DONE = 'INDEX_PAGE_LOAD_DATA_DONE';
export const INDEX_PAGE_LOAD_DATA_FAILURE = 'INDEX_PAGE_LOAD_DATA_FAILURE';
